#실제 운영될 환경에서 사용할 설정
spring:
  profiles:
    include: oauth, real-db

  jpa:
    properties:
      hibernate:
        #        dialect: org.hibernate.dialect.MySQL5InnoDBDialect #Spring Boot 버전업에 따른 변화(AS-IS)
        dialect: org.hibernate.dialect.MySQL57Dialect       #TO-BE
        storage_engine: innodb                              #TO-BE

  session:
    store-type: jdbc